version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y nodejs
      - apt-get install -y npm
      - npm install -g grunt-cli
  build:
    commands:
      - echo Build started on `date`
      - gradle build 
artifacts:
  files:
    - '**/*'
#  discard-paths: yes